version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@latest
  pre_build:
    commands:
      - echo Installing project dependencies...
      - npm ci
  build:
    commands:
      - echo Building Angular application...
      - echo Checking Angular version...
      - npx ng version
      - echo Checking system resources...
      - free -h
      - df -h
      - echo Building with full error output...
      - set +e
      - echo "Checking TypeScript compilation..."
      - npx tsc --noEmit || echo "TypeScript check completed with warnings"
      - echo "Trying development build first..."
      - npx ng build --configuration development
      - echo "Development build completed, trying production with memory limit..."
      - NODE_OPTIONS=--max_old_space_size=4096 npx ng build --configuration production --verbose
      - BUILD_EXIT_CODE=$?
      - echo "Build exit code was $BUILD_EXIT_CODE"
      - set -e
      - echo Checking if any files were created...
      - ls -la dist/ || echo "No dist folder found"
      - if [ $BUILD_EXIT_CODE -ne 0 ]; then echo "Build failed but continuing..."; fi
  post_build:
    commands:
      - echo Build completed successfully!
artifacts:
  files:
    - '**/*'
  base-directory: dist/angularfolder
