version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@latest
  pre_build:
    commands:
      - echo Installing project dependencies...
      - npm ci
  build:
    commands:
      - echo Building Angular application...
      - echo Trying development build first...
      - npx ng build --configuration development
      - echo Development build successful, trying production...
      - npx ng build --configuration production
      - echo Listing build output...
      - ls -la dist/
  post_build:
    commands:
      - echo Build completed successfully!
artifacts:
  files:
    - '**/*'
  base-directory: dist/angularfolder
