version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@latest
  pre_build:
    commands:
      - echo Installing project dependencies...
      - npm ci
  build:
    commands:
      - echo Building Angular application...
      - echo Checking package.json scripts...
      - cat package.json | grep -A 10 '"scripts"'
      - echo Using npm run build...
      - npm run build
      - echo Listing build output...
      - ls -la dist/
  post_build:
    commands:
      - echo Build completed successfully!
artifacts:
  files:
    - '**/*'
  base-directory: dist/angularfolder
