version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing Angular CLI"
      - npm install -g @angular/cli@20
      - npm ci
  build:
    commands:
      - echo "Building Angular in production mode"
      - ng build --configuration production
  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync dist/angularfolder/browser/ s3://awsdynasty --delete
      - echo "Deployment completed"
artifacts:
  base-directory: dist/angularfolder/browser
  files:
    - '**/*'
