version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@latest
  pre_build:
    commands:
      - echo Installing project dependencies...
      - npm ci
  build:
    commands:
      - echo Building Angular application...
      - echo Checking Angular version...
      - npx ng version
      - echo Checking system resources...
      - free -h
      - df -h
      - echo Building with full error output...
      - set +e
      - echo "Building Angular app with development config..."
      - npx ng build --configuration development
      - echo "Build completed successfully!"
      - echo Checking build output...
      - ls -la dist/
  post_build:
    commands:
      - echo Build completed successfully!
artifacts:
  files:
    - '**/*'
  base-directory: dist
