version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@latest
  pre_build:
    commands:
      - echo Installing project dependencies...
      - npm ci
  build:
    commands:
      - echo Building Angular application...
      - echo Checking Angular version...
      - npx ng version
      - echo Building with full error output...
      - npx ng build --configuration production --verbose 2>&1 || echo "Build failed with exit code $?"
      - echo Checking if any files were created...
      - ls -la dist/ || echo "No dist folder found"
  post_build:
    commands:
      - echo Build completed successfully!
artifacts:
  files:
    - '**/*'
  base-directory: dist/angularfolder
