version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing Angular CLI..."
      - npm install -g @angular/cli@latest
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Checking Angular version..."
      - ng version
  build:
    commands:
      - echo "Building Angular app..."
      - ng build --configuration production
      - echo "Listing build output..."
      - ls -la dist/
artifacts:
  files:
    - '**/*'
  base-directory: dist
