version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@16
      - npm ci
  build:
    commands:
      - echo "Generating version file"
      - |
        # Get git commit count for version increment
        GIT_COMMIT_COUNT=$(git rev-list --count HEAD 2>/dev/null || echo "1")
        MAJOR_VERSION="4"
        MINOR_VERSION=$((GIT_COMMIT_COUNT % 100))
        VERSION="v${MAJOR_VERSION}.${MINOR_VERSION}.${CODEBUILD_BUILD_NUMBER:-1}"
        BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S UTC')
        echo "{\"version\": \"$VERSION\", \"buildDate\": \"$BUILD_DATE\", \"buildNumber\": \"$CODEBUILD_BUILD_NUMBER\"}" > src/assets/version.json
        echo "Generated version: $VERSION"
      - ng build --configuration production
      - echo "Creating assets directory and copying version.json"
      - mkdir -p dist/angularfolder/browser/assets
      - cp src/assets/version.json dist/angularfolder/browser/assets/version.json
      - echo "Build output structure:"
      - ls -la dist/angularfolder/browser/
      - ls -la dist/angularfolder/browser/assets/
  post_build:
    commands:
      - echo "Build completed successfully"
      - cat src/assets/version.json
      - aws s3 sync dist/angularfolder/browser/ s3://awsdynasty --delete
      - echo "Invalidating CloudFront cache for version.json"
      - aws cloudfront create-invalidation --distribution-id E1234567890 --paths "/assets/version.json" || echo "CloudFront invalidation failed or not configured"
      - echo "Deployment completed with version $(cat src/assets/version.json | grep -o '"version":"[^"]*' | cut -d'"' -f4)"
artifacts:
  base-directory: dist/angularfolder/browser
  files:
    - "**/*"