version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli@16
      - npm ci
  build:
    commands:
      - sed -i "s/version = .*\;/version = 'v3.0-$CODEBUILD_BUILD_NUMBER';/" src/app/dashboard/dashboard.ts
      - ng build --configuration production
  post_build:
    commands:
      - aws s3 sync dist/angularfolder/browser/ s3://awsdynasty --delete
artifacts:
  base-directory: dist/angularfolder/browser
  files:
    - "**/*"