version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Installing npm packages...
      - npm install
  build:
    commands:
      - echo Building Angular app...
      - npx ng build --configuration production
  post_build:
    commands:
      - echo Build completed successfully
      - echo Artifacts ready for deployment
artifacts:
  files:
    - '**/*'
  base-directory: dist/angularfolder
