version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo "Using ng build directly..."
      - ng build
      - echo "Build completed, checking output..."
      - ls -la dist/
artifacts:
  files:
    - '**/*'
  base-directory: dist/angularfolder
